import {
  AlignLeft,
  LayoutGrid,
  Image,
  Layers,
  MessageSquare,
  HardDrive,
  ShoppingBag,
  FileText,
  Puzzle,
  Folder,
  Film,
  FileArchive,
  Type,
  MousePointerClick,
  Square,
  Smile,
  Minus,
  ClipboardList,
  Package,
  Play,
  List,
  GalleryHorizontal,
  PanelTop,
  Frame,
  ChevronsDown,
  Table,
  PlusSquare,
  Layout,
  ShoppingCart,
  Timer,
  Code,
  MapPin,
  Share2,
  Star,
  BarChart2,
  HelpCircle,
  Bookmark,
  Copy,
  Rocket,
} from "lucide-react";
import type { ComponentType } from "react";

type IconComponent = ComponentType<{ className?: string }>;

const ICON_MAP: Record<string, IconComponent> = {
  "align-left": AlignLeft,
  "layout-grid": LayoutGrid,
  bookmark: Bookmark,
  image: Image,
  layers: Layers,
  "message-square": MessageSquare,
  "hard-drive": HardDrive,
  "shopping-bag": ShoppingBag,
  "file-text": FileText,
  puzzle: Puzzle,
  folder: Folder,
  film: Film,
  "file-archive": FileArchive,
  type: Type,
  "mouse-pointer-click": MousePointerClick,
  square: Square,
  smile: Smile,
  minus: Minus,
  "clipboard-list": ClipboardList,
  package: Package,
  play: Play,
  list: List,
  "gallery-horizontal": GalleryHorizontal,
  "panel-top": PanelTop,
  frame: Frame,
  "chevrons-down": ChevronsDown,
  table: Table,
  "plus-square": PlusSquare,
  layout: Layout,
  "shopping-cart": ShoppingCart,
  timer: Timer,
  code: Code,
  "map-pin": MapPin,
  "share-2": Share2,
  star: Star,
  "bar-chart-2": BarChart2,
  rocket: Rocket,
};

const FALLBACK = HelpCircle;

export function getLucideIcon(name: string, className = "w-4 h-4"): React.ReactNode {
  const Icon = ICON_MAP[name] ?? FALLBACK;
  return <Icon className={className} />;
}

export { FALLBACK as HelpCircleIcon };
