/**
 * Catalog đầy đủ các template từ thư mục "pages mẫu/".
 * Files HTML được phục vụ tĩnh từ /public/templates/ qua Vite.
 *
 * JsonContent dùng html-code element (subType: "iframe") trỏ thẳng tới file HTML —
 * toàn bộ CSS / JS / ảnh tương đối vẫn hoạt động bình thường.
 */

import type { TemplateItem } from "@/lib/shared/api";

function makeIframeJsonContent(iframeSrc: string): string {
  return JSON.stringify({
    sections: [
      {
        id: 1,
        pageId: 0,
        order: 1,
        height: 8000,
        visible: true,
        isLocked: false,
        name: "Template",
        backgroundColor: null,
        backgroundImageUrl: null,
        elements: [
          {
            id: 1,
            sectionId: 1,
            type: "html-code",
            order: 1,
            x: 0,
            y: 0,
            width: 960,
            height: 8000,
            zIndex: 1,
            rotation: 0,
            opacity: 1,
            isLocked: false,
            isHidden: false,
            content: JSON.stringify({ subType: "iframe", iframeSrc }),
            styles: { fullScreen: true },
          },
        ],
      },
    ],
  });
}

export type StaticTemplateItem = TemplateItem & {
  previewUrl: string;
  jsonContent: string;
};

export const STATIC_TEMPLATES: StaticTemplateItem[] = [
  // ════════════════════════════════════════════════════════
  // MobApp — App Landing Page
  // ════════════════════════════════════════════════════════
  {
    id: 1001,
    name: "MobApp — Landing Page Ứng Dụng",
    category: "Công nghệ",
    description: "Landing page giới thiệu ứng dụng mobile với hero, tính năng nổi bật, screenshots và nút tải app.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 420,
    createdAt: "2024-01-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/mobapp-master/index.html",
    jsonContent: makeIframeJsonContent("/templates/mobapp-master/index.html"),
  },

  // ════════════════════════════════════════════════════════
  // Tasty — Restaurant / Food
  // ════════════════════════════════════════════════════════
  {
    id: 1002,
    name: "Tasty — Trang Chủ Nhà Hàng",
    category: "Nhà hàng",
    description: "Trang chủ nhà hàng với hero banner, menu nổi bật, câu chuyện thương hiệu và khu đặt bàn.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 380,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/index.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/index.html"),
  },
  {
    id: 1003,
    name: "Tasty — Thực Đơn",
    category: "Nhà hàng",
    description: "Trang thực đơn phân loại theo danh mục, hiển thị ảnh món ăn và giá hấp dẫn.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 210,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/menu.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/menu.html"),
  },
  {
    id: 1004,
    name: "Tasty — Đặt Bàn",
    category: "Nhà hàng",
    description: "Trang đặt bàn trực tuyến với form ngày giờ, số khách và xác nhận tự động.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 175,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/reservation.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/reservation.html"),
  },
  {
    id: 1005,
    name: "Tasty — Gallery Món Ăn",
    category: "Nhà hàng",
    description: "Trang gallery trình bày ảnh món ăn và không gian nhà hàng theo dạng lưới đẹp.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 142,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/gallery.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/gallery.html"),
  },
  {
    id: 1006,
    name: "Tasty — Giới Thiệu",
    category: "Nhà hàng",
    description: "Trang about us: câu chuyện thương hiệu, đội ngũ đầu bếp và triết lý ẩm thực.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 118,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/about.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/about.html"),
  },
  {
    id: 1007,
    name: "Tasty — Liên Hệ",
    category: "Nhà hàng",
    description: "Trang liên hệ với bản đồ, địa chỉ, giờ mở cửa và form gửi tin nhắn.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 96,
    createdAt: "2024-02-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/tasty-master/contact.html",
    jsonContent: makeIframeJsonContent("/templates/tasty-master/contact.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — Landing / Agency / Finance (live/)
  // ════════════════════════════════════════════════════════
  {
    id: 2001,
    name: "Titan — Agency Landing",
    category: "Agency",
    description: "Landing page agency hiện đại, multi-section với hero fullscreen, dịch vụ, portfolio và form liên hệ.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 510,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_agency.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_agency.html"),
  },
  {
    id: 2002,
    name: "Titan — Finance Landing",
    category: "Tài chính",
    description: "Landing page tài chính / fintech chuyên nghiệp với bảng giá, thống kê và testimonial.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 340,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_finance.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_finance.html"),
  },
  {
    id: 2003,
    name: "Titan — Multipurpose Landing",
    category: "Landing Page",
    description: "Landing page đa năng: hero nổi bật, tính năng sản phẩm, bảng giá và CTA mạnh.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 620,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_landing.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_landing.html"),
  },
  {
    id: 2004,
    name: "Titan — Classic Flexslider",
    category: "Landing Page",
    description: "Landing page với slider cuộn mượt, giới thiệu sản phẩm theo phong cách cổ điển.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 185,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_mp_classic_flexslider.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_mp_classic_flexslider.html"),
  },
  {
    id: 2005,
    name: "Titan — Classic Gradient Overlay",
    category: "Landing Page",
    description: "Landing page hero toàn màn hình với gradient overlay ấn tượng và nội dung tập trung.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 198,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_mp_classic_gradient_overlay.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_mp_classic_gradient_overlay.html"),
  },
  {
    id: 2006,
    name: "Titan — Classic Static",
    category: "Landing Page",
    description: "Landing page hero tĩnh, tối giản, phù hợp sản phẩm đơn giản cần thông điệp rõ ràng.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 154,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_mp_classic_static.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_mp_classic_static.html"),
  },
  {
    id: 2007,
    name: "Titan — Classic Text Rotator",
    category: "Landing Page",
    description: "Landing page với tiêu đề xoay động, thu hút sự chú ý và truyền tải nhiều thông điệp.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 167,
    createdAt: "2024-03-01T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/index_mp_classic_text_rotator.html",
    jsonContent: makeIframeJsonContent("/templates/live/index_mp_classic_text_rotator.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — About Us (5 biến thể)
  // ════════════════════════════════════════════════════════
  {
    id: 2101,
    name: "Titan — About Us v1",
    category: "Dịch vụ",
    description: "Trang giới thiệu công ty phong cách tối giản: sứ mệnh, đội ngũ và các số liệu nổi bật.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 132,
    createdAt: "2024-03-05T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/about1.html",
    jsonContent: makeIframeJsonContent("/templates/live/about1.html"),
  },
  {
    id: 2102,
    name: "Titan — About Us v2",
    category: "Dịch vụ",
    description: "Trang about với timeline lịch sử phát triển, ảnh đội ngũ và giá trị cốt lõi.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 118,
    createdAt: "2024-03-05T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/about2.html",
    jsonContent: makeIframeJsonContent("/templates/live/about2.html"),
  },
  {
    id: 2103,
    name: "Titan — About Us v3",
    category: "Dịch vụ",
    description: "Trang giới thiệu sáng tạo với video background, thành tựu và câu chuyện thương hiệu.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 109,
    createdAt: "2024-03-05T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/about3.html",
    jsonContent: makeIframeJsonContent("/templates/live/about3.html"),
  },
  {
    id: 2104,
    name: "Titan — About Us v4",
    category: "Dịch vụ",
    description: "Trang about với layout 2 cột ngang, ảnh lớn và copy ngắn gọn súc tích.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 97,
    createdAt: "2024-03-05T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/about4.html",
    jsonContent: makeIframeJsonContent("/templates/live/about4.html"),
  },
  {
    id: 2105,
    name: "Titan — About Us v5",
    category: "Dịch vụ",
    description: "Trang about phong cách bold: số liệu khổng lồ, testimonial và CTA tuyển dụng.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 88,
    createdAt: "2024-03-05T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/about5.html",
    jsonContent: makeIframeJsonContent("/templates/live/about5.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — Contact (3 biến thể)
  // ════════════════════════════════════════════════════════
  {
    id: 2201,
    name: "Titan — Contact v1",
    category: "Liên hệ",
    description: "Trang liên hệ đơn giản với form, địa chỉ, số điện thoại và bản đồ Google Maps.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 145,
    createdAt: "2024-03-10T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/contact1.html",
    jsonContent: makeIframeJsonContent("/templates/live/contact1.html"),
  },
  {
    id: 2202,
    name: "Titan — Contact v2",
    category: "Liên hệ",
    description: "Trang liên hệ với hero section, nhiều phương thức liên hệ và FAQ tích hợp.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 128,
    createdAt: "2024-03-10T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/contact2.html",
    jsonContent: makeIframeJsonContent("/templates/live/contact2.html"),
  },
  {
    id: 2203,
    name: "Titan — Contact v3",
    category: "Liên hệ",
    description: "Trang liên hệ đầy đủ: bản đồ toàn màn hình, form nổi và thông tin chi nhánh.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 113,
    createdAt: "2024-03-10T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/contact3.html",
    jsonContent: makeIframeJsonContent("/templates/live/contact3.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — Blog Grid
  // ════════════════════════════════════════════════════════
  {
    id: 2301,
    name: "Titan — Blog Lưới 2 Cột",
    category: "Blog",
    description: "Trang blog dạng lưới 2 cột rộng, tập trung ảnh thumbnail lớn và tiêu đề nổi bật.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 210,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_col_2.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_col_2.html"),
  },
  {
    id: 2302,
    name: "Titan — Blog Lưới 3 Cột",
    category: "Blog",
    description: "Trang blog dạng lưới 3 cột, cân bằng giữa số lượng bài và khả năng đọc.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 289,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_col_3.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_col_3.html"),
  },
  {
    id: 2303,
    name: "Titan — Blog Lưới 4 Cột",
    category: "Blog",
    description: "Trang blog dạng lưới 4 cột dày đặc, tối ưu cho nhiều nội dung và sidebar.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 178,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_col_4.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_col_4.html"),
  },
  {
    id: 2304,
    name: "Titan — Blog Masonry 2 Cột",
    category: "Blog",
    description: "Blog dạng masonry 2 cột, bài viết cao thấp xen kẽ tạo layout sinh động.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 156,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_masonry_col_2.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_masonry_col_2.html"),
  },
  {
    id: 2305,
    name: "Titan — Blog Masonry 3 Cột",
    category: "Blog",
    description: "Blog dạng masonry 3 cột — định dạng Pinterest, mỗi bài có chiều cao khác nhau.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 201,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_masonry_col_3.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_masonry_col_3.html"),
  },
  {
    id: 2306,
    name: "Titan — Blog Masonry 4 Cột",
    category: "Blog",
    description: "Blog masonry 4 cột dày đặc, tạo ra một tường nội dung phong phú và cuốn hút.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 142,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_grid_masonry_col_4.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_grid_masonry_col_4.html"),
  },
  {
    id: 2307,
    name: "Titan — Blog Single (Sidebar Trái)",
    category: "Blog",
    description: "Trang bài viết chi tiết với sidebar trái: danh mục, bài liên quan và widget tìm kiếm.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 134,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_single_left_sidebar.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_single_left_sidebar.html"),
  },
  {
    id: 2308,
    name: "Titan — Blog Single (Sidebar Phải)",
    category: "Blog",
    description: "Trang bài viết chi tiết với sidebar phải: tag cloud, bài mới nhất và quảng cáo.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 147,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_single_right_sidebar.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_single_right_sidebar.html"),
  },
  {
    id: 2309,
    name: "Titan — Blog Standard (Sidebar Trái)",
    category: "Blog",
    description: "Blog danh sách chuẩn với sidebar trái, mỗi bài hiển thị ảnh + đoạn trích.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 119,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_standard_left_sidebar.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_standard_left_sidebar.html"),
  },
  {
    id: 2310,
    name: "Titan — Blog Standard (Sidebar Phải)",
    category: "Blog",
    description: "Blog danh sách chuẩn với sidebar phải, bố cục truyền thống dễ đọc và quen thuộc.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 127,
    createdAt: "2024-03-15T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/blog_standard_right_sidebar.html",
    jsonContent: makeIframeJsonContent("/templates/live/blog_standard_right_sidebar.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — Gallery (4 biến thể)
  // ════════════════════════════════════════════════════════
  {
    id: 2401,
    name: "Titan — Gallery 2 Cột",
    category: "Gallery",
    description: "Trang gallery ảnh 2 cột lớn, phù hợp portfolio sáng tạo hoặc triển lãm nhiếp ảnh.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 158,
    createdAt: "2024-03-20T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/gallery_col_2.html",
    jsonContent: makeIframeJsonContent("/templates/live/gallery_col_2.html"),
  },
  {
    id: 2402,
    name: "Titan — Gallery 3 Cột",
    category: "Gallery",
    description: "Gallery 3 cột cân đối, hiển thị nhiều ảnh với hover effect và lightbox.",
    designType: "responsive",
    isFeatured: true,
    isPremium: false,
    usageCount: 234,
    createdAt: "2024-03-20T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/gallery_col_3.html",
    jsonContent: makeIframeJsonContent("/templates/live/gallery_col_3.html"),
  },
  {
    id: 2403,
    name: "Titan — Gallery 4 Cột",
    category: "Gallery",
    description: "Gallery 4 cột dày đặc, tối ưu cho portfolio lớn và thư viện ảnh nhiều mục.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 189,
    createdAt: "2024-03-20T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/gallery_col_4.html",
    jsonContent: makeIframeJsonContent("/templates/live/gallery_col_4.html"),
  },
  {
    id: 2404,
    name: "Titan — Gallery 6 Cột",
    category: "Gallery",
    description: "Gallery 6 cột miniature, tạo mosaic ảnh đẹp mắt cho website thời trang hay thiết kế.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 143,
    createdAt: "2024-03-20T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/gallery_col_6.html",
    jsonContent: makeIframeJsonContent("/templates/live/gallery_col_6.html"),
  },

  // ════════════════════════════════════════════════════════
  // Titan — FAQ
  // ════════════════════════════════════════════════════════
  {
    id: 2501,
    name: "Titan — FAQ / Câu Hỏi Thường Gặp",
    category: "Dịch vụ",
    description: "Trang FAQ với accordion expand/collapse, thanh tìm kiếm và phân loại câu hỏi theo chủ đề.",
    designType: "responsive",
    isFeatured: false,
    isPremium: false,
    usageCount: 196,
    createdAt: "2024-03-25T00:00:00Z",
    thumbnailUrl: undefined,
    previewUrl: "/templates/live/faq.html",
    jsonContent: makeIframeJsonContent("/templates/live/faq.html"),
  },
];

/** Danh sách categories duy nhất từ static templates */
export function getStaticCategories(): string[] {
  return [...new Set(STATIC_TEMPLATES.map((t) => t.category))].sort();
}

/** Lọc và sort static templates (dùng trong DashboardTemplates khi không có API) */
export function filterStaticTemplates(params?: {
  category?: string;
  search?: string;
  designType?: string;
  featured?: boolean;
}): StaticTemplateItem[] {
  let list = [...STATIC_TEMPLATES];
  if (params?.category) list = list.filter((t) => t.category === params.category);
  if (params?.search) {
    const q = params.search.toLowerCase();
    list = list.filter(
      (t) =>
        t.name.toLowerCase().includes(q) ||
        (t.description ?? "").toLowerCase().includes(q) ||
        t.category.toLowerCase().includes(q),
    );
  }
  if (params?.designType) list = list.filter((t) => t.designType === params.designType);
  if (params?.featured) list = list.filter((t) => t.isFeatured);
  return list.sort((a, b) => b.usageCount - a.usageCount);
}
