// <auto-generated />
using System;
using LadiPage.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LadiPage.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414030509_AddEditorDataTables")]
    partial class AddEditorDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LadiPage.Domain.Entities.CustomDomain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaTenMien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenMien");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayXacMinh");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("TenMien", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NhomKhach");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhachHang");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NguonKhach");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaQuan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenQuan");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("MaTinh");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("QuanHuyen", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.EditorIcon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBieuTuong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DanhMuc");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KyTu");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauSac");

                    b.Property<string>("IconId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaIcon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenBieuTuong");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .IsUnique();

                    b.ToTable("BieuTuongEditor", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ElementPreset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMau");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DefaultContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungMacDinh");

                    b.Property<int?>("DefaultHeight")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCaoMacDinh");

                    b.Property<int?>("DefaultWidth")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRongMacDinh");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMau");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("StylesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KieuDangJson");

                    b.Property<string>("TabName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenTab");

                    b.Property<long>("ToolItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaMuc");

                    b.HasKey("Id");

                    b.HasIndex("ToolItemId");

                    b.ToTable("MauPhanTuMacDinh", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.FormConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaForm");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("EmailNotify")
                        .HasColumnType("bit")
                        .HasColumnName("ThongBaoEmail");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TruongDuLieuJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenForm");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("WebhookUrl");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("CauHinhForm", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.FormPresetTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMauForm");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccentColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauNhan");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauNen");

                    b.Property<string>("ButtonColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauNut");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ChuNut");

                    b.Property<string>("ButtonTextColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauChuNut");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CacTruongJson");

                    b.Property<int?>("FormBorderRadius")
                        .HasColumnType("int")
                        .HasColumnName("GocBoForm");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiForm");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<int?>("InputRadius")
                        .HasColumnType("int")
                        .HasColumnName("GocBoInput");

                    b.Property<string>("InputStyle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KieuInput");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMauForm");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("PresetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaPreset");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTab");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("TitleColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauTieuDe");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.HasKey("Id");

                    b.HasIndex("PresetId")
                        .IsUnique();

                    b.ToTable("MauFormSanDung", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Lead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaLead");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuLieuJson");

                    b.Property<long?>("FormId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaForm");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DiaChiIP");

                    b.Property<long?>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("PageId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("DuLieuLead", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.LinePresetDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDuongKe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauSac");

                    b.Property<string>("DashArrayJson")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KieuGachJson");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMau");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("PresetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaPreset");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KieuDuong");

                    b.Property<string>("Tab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tab");

                    b.Property<int>("Thickness")
                        .HasColumnType("int")
                        .HasColumnName("DoDay");

                    b.HasKey("Id");

                    b.HasIndex("PresetId")
                        .IsUnique();

                    b.ToTable("MauDuongKe", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.LoginFeatureSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTinhNang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("SlideId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaSlide");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.HasKey("Id");

                    b.ToTable("TinhNangDangNhap", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaTaiNguyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTaAlt");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LoaiNoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TenFile");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("KichThuoc");

                    b.Property<string>("Folder")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThuMuc");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TenGoc");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AnhThuNho");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DuongDan");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.Property<long?>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TaiNguyen", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.MomoPaymentOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaGiaoDich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("SoTien");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHoanThanh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("MomoTransId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaGiaoDichMoMo");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaDonHang");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoi");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaYeuCau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("GiaoDichThanhToanMoMo", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaThongBao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("DaDoc");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("NoiDung");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Loai");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaDonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TongTien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhachHang");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailKhachHang");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SdtKhachHang");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaSanPham");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TrangThaiDonHang");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Page", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiTao");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<string>("Favicon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Favicon");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungHtml");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungTrang");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTaMetaTag");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TuKhoaMetaTag");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TieuDeMetaTag");

                    b.Property<bool>("MobileFriendly")
                        .HasColumnType("bit")
                        .HasColumnName("ThuanThietBiDiDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenTrang");

                    b.Property<string>("PagePassword")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MatKhauTrang");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LoaiTrang");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDang");

                    b.Property<byte?>("SeoScore")
                        .HasColumnType("tinyint")
                        .HasColumnName("DiemSEO");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DuongDan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaMauTrang");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("Trang", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaPhanTu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LienKet");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DuongDanAnh");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("DaAn");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("DaKhoa");

                    b.Property<double>("Opacity")
                        .HasColumnType("float")
                        .HasColumnName("DoMo");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<double>("Rotation")
                        .HasColumnType("float")
                        .HasColumnName("GocXoay");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaSection");

                    b.Property<string>("StylesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KieuDangJson");

                    b.Property<string>("Target")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Loai");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DuongDanVideo");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("ViTriX");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("ViTriY");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int")
                        .HasColumnName("ZIndex");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("TrangPhanTu", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaSection");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MauNen");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhNen");

                    b.Property<string>("CustomClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LopTuyChinh");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("DaKhoa");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("HienThi");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSection");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "Order");

                    b.ToTable("TrangSection", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageTag", b =>
                {
                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNhan");

                    b.HasKey("PageId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TrangNhan", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ChuKyThanhToan");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("HasAbTest")
                        .HasColumnType("bit")
                        .HasColumnName("CoABTest");

                    b.Property<bool>("HasAi")
                        .HasColumnType("bit")
                        .HasColumnName("CoAI");

                    b.Property<bool>("HasAutomation")
                        .HasColumnType("bit")
                        .HasColumnName("CoTuDongHoa");

                    b.Property<bool>("HasCustomDomain")
                        .HasColumnType("bit")
                        .HasColumnName("CoTenMienRieng");

                    b.Property<bool>("HasEcommerce")
                        .HasColumnType("bit")
                        .HasColumnName("CoBanHang");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int")
                        .HasColumnName("SoThanhVienToiDa");

                    b.Property<long?>("MaxPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("SoLuotTruyCapToiDa");

                    b.Property<int>("MaxPages")
                        .HasColumnType("int")
                        .HasColumnName("SoTrangToiDa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenGoi");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("GiaTien");

                    b.Property<decimal>("StorageGb")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("DungLuongGB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("GoiDichVu", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PlanSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaDangKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SoTienDaThanhToan");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit")
                        .HasColumnName("TuDongGiaHan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DonViTien");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoi");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MaGiaoDich");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("DangKyGoi", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PopupTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMauPopup");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DanhMuc");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMauPopup");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("StylesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StylesJson");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaTemplate");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhThuNho");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("MauPopup", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DanhMuc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhSanPham");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenSanPham");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("GiaTien");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("GiaKhuyenMai");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("TonKho");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTinh");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("TinhThanh", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.SampleVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaVideo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmbedUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DuongDanNhung");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenVideo");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NguonVideo");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhThuNho");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DuongDan");

                    b.HasKey("Id");

                    b.ToTable("VideoMau", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaPhien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DiaChiIP");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("TokenLamMoi");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Token");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ThongTinTrinh");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PhienDangNhap", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.StockImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaAnh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TacGia");

                    b.Property<string>("AuthorUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DuongDanTacGia");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DanhMuc");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenAnh");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NguonAnh");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DuongDan");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.HasKey("Id");

                    b.ToTable("AnhMauCoBan", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNhan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MauSac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNhan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("NhanDan", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMau");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DanhMuc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTa");

                    b.Property<string>("DesignType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("responsive")
                        .HasColumnName("LoaiThietKe");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("NoiBat");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("LaPro");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMau");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SoLuotDung");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("MauGiaoDien", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ToolCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaDanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BieuTuong");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("HoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDanhMuc");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("CongCuDanhMuc", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ToolItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaDanhMuc");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiPhanTu");

                    b.Property<bool>("HasSubTabs")
                        .HasColumnType("bit")
                        .HasColumnName("CoTabCon");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BieuTuong");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("HoatDong");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenMuc");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("SubTabsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TabConJson");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CongCuMuc", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("CurrentPlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoiHienTai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailDaXacNhan");

                    b.Property<DateTime?>("EmailVerificationSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGuiXacThucEmail");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MaXacThucEmail");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HoTen");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LanDangNhapCuoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("MatKhauMaHoa");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("SdtDaXacNhan");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHanGoi");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaGioiThieu");

                    b.Property<long?>("ReferredByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DuocGioiThieuBoi");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhuong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("MaQuan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenPhuong");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("PhuongXa", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QuocGia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QuanHuyen");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("LaMacDinh");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhongGian");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaChuSoHuu");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoiDichVu");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaBuuDien");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TinhThanh");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DuongDan");

                    b.Property<string>("StoreAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChiCuaHang");

                    b.Property<string>("StoreCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DonViTienKhongGian");

                    b.Property<string>("StorePhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SoDienThoaiCuaHang");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MuiGio");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PhuongXa");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("KhongGianLamViec", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaThanhVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DuocMoiBoi");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThamGia");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("ThanhVienKhongGian", (string)null);
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.CustomDomain", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Customer", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.District", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ElementPreset", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.ToolItem", "ToolItem")
                        .WithMany("Presets")
                        .HasForeignKey("ToolItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolItem");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.FormConfig", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Lead", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.FormConfig", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LadiPage.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Page");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Media", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.MomoPaymentOrder", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Notification", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Order", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Page", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageElement", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.PageSection", "Section")
                        .WithMany("Elements")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageSection", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageTag", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PlanSubscription", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Product", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Session", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Tag", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ToolItem", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.ToolCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.User", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.Plan", "CurrentPlan")
                        .WithMany()
                        .HasForeignKey("CurrentPlanId");

                    b.Navigation("CurrentPlan");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Ward", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("Owner");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("LadiPage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LadiPage.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.PageSection", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ToolCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LadiPage.Domain.Entities.ToolItem", b =>
                {
                    b.Navigation("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
