// <auto-generated />
using System;
using LadiPage.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LadiPage.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312092414_AddPageSections")]
    partial class AddPageSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LadiPage.Core.Entities.Page", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungHtml");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenTrang");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DuongDan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("Trang", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PageElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaPhanTu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LienKet");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaSection");

                    b.Property<string>("StylesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KieuDangJson");

                    b.Property<string>("Target")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Loai");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("ChieuRong");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("ViTriX");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("ViTriY");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int")
                        .HasColumnName("ZIndex");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("TrangPhanTu", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PageSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaSection");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MauNen");

                    b.Property<string>("CustomClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LopTuyChinh");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("ChieuCao");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("HienThi");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaTrang");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "Order");

                    b.ToTable("TrangSection", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ChuKyThanhToan");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("HasAbTest")
                        .HasColumnType("bit")
                        .HasColumnName("CoABTest");

                    b.Property<bool>("HasAi")
                        .HasColumnType("bit")
                        .HasColumnName("CoAI");

                    b.Property<bool>("HasAutomation")
                        .HasColumnType("bit")
                        .HasColumnName("CoTuDongHoa");

                    b.Property<bool>("HasCustomDomain")
                        .HasColumnType("bit")
                        .HasColumnName("CoTenMienRieng");

                    b.Property<bool>("HasEcommerce")
                        .HasColumnType("bit")
                        .HasColumnName("CoBanHang");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("DangHoatDong");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int")
                        .HasColumnName("SoThanhVienToiDa");

                    b.Property<long?>("MaxPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("SoLuotTruyCapToiDa");

                    b.Property<int>("MaxPages")
                        .HasColumnType("int")
                        .HasColumnName("SoTrangToiDa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenGoi");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("GiaTien");

                    b.Property<decimal>("StorageGb")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("DungLuongGB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("GoiDichVu", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PlanSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaDangKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SoTienDaThanhToan");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit")
                        .HasColumnName("TuDongGiaHan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DonViTien");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoi");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MaGiaoDich");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("DangKyGoi", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaPhien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DiaChiIP");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("TokenLamMoi");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Token");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ThongTinTrinh");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PhienDangNhap", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaMau");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DanhMuc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenMau");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("MauGiaoDien", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("CurrentPlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoiHienTai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailDaXacNhan");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HoTen");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LanDangNhapCuoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("MatKhauMaHoa");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("SdtDaXacNhan");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHanGoi");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaGioiThieu");

                    b.Property<long?>("ReferredByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DuocGioiThieuBoi");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("LaMacDinh");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhongGian");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaChuSoHuu");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaGoiDichVu");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DuongDan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("KhongGianLamViec", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.WorkspaceMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaThanhVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DuocMoiBoi");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThamGia");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaNguoiDung");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("MaKhongGian");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("ThanhVienKhongGian", (string)null);
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Page", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PageElement", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.PageSection", "Section")
                        .WithMany("Elements")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PageSection", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PlanSubscription", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LadiPage.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Session", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.User", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.Plan", "CurrentPlan")
                        .WithMany()
                        .HasForeignKey("CurrentPlanId");

                    b.Navigation("CurrentPlan");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Workspace", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LadiPage.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("Owner");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("LadiPage.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LadiPage.Core.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("LadiPage.Core.Entities.PageSection", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
